import pyperclip


companies = [
"(ISC)²",
"10 Minute School",
"10 by 10",
"140 Proof",
"15Five",
"21Tech",
"21st Century Fox",
"23andMe",
"24 Seven Talent",
"2600Hz",
"3 Corações S/A",
"3M",
"3scale",
"500 Startups",
"80Twenty",
"8tracks",
"99",
"99designs",
"A-Mark Precious Metals",
"A.C.Camargo Cancer Center",
"ABA Journal",
"ABB Power Grids",
"ABM Industries",
"ABRE - Estágio Emprego",
"ACWA Power",
"ADM",
"ADP",
"AECOM",
"AES",
"AEye",
"AFRY",
"AGCO Corporation",
"AGCO",
"AICPA",
"AIG",
"AK Steel Holding",
"AKQA",
"ALEXBANK",
"AMD",
"AMEC",
"AMERICAN EAGLE OUTFITTERS INC.",
"ANBIMA",
"AOL",
"ASME (The American Society of Mechanical Engineers)",
"ASML",
"ASOS.com",
"ASUS",
"AT&T",
"AXA Gulf",
"AbbVie",
"Abbott Laboratories",
"Abbott",
"Abercrombie & Fitch Co.",
"Abl Schools",
"Abril",
"Abstract",
"Abunayyan Holding",
"Accela",
"Accenture",
"Accor",
"Accounting Today",
"Aché Laboratórios",
"Acne Studios AB",
"Activision Blizzard",
"Activision",
"Ad Age",
"AdRoll",
"AdStage",
"Adani Group",
"Addepar",
"Addison Group",
"Adecco",
"Adidas",
"Administradores.com",
"Admitsee",
"Adobe",
"Advance Auto Parts",
"Advanced Micro Devices",
"Advent Software",
"Adweek",
"Adyen",
"Aerotek",
"Aetna, a CVS Health Company",
"Affinity",
"Affirm",
"Aflac",
"Africa Confidential",
"African Development Bank Group",
"African Union",
"After College",
"Agilent Technologies",
"Agility",
"Agoda",
"Air Liquide",
"Air Products & Chemicals",
"Air Products",
"Airbnb",
"Airbus Defence and Space",
"Airbus Helicopters",
"Airswift",
"Airtable",
"Airware",
"Ajilon",
"Ajinomoto do Brasil Industria e Comércio de Alimentos Ltda.",
"Akamai Technologies",
"Aktana",
"AkzoNobel",
"Al Jazeera Media Network",
"Al Rajhi Bank",
"Al-Futtaim",
"Alaska Air Group",
"Alaska Airlines",
"Albertsons",
"Alcoa",
"Alcon",
"Alelo Brasil",
"Alexion Pharmaceuticals, Inc.",
"Alfa Laval",
"Alfanar",
"Algar Tech",
"Algar Telecom",
"Alghanim Industries",
"Algolia",
"Algérie Télécom",
"Alibaba.com",
"Alicorp",
"AlienVault",
"Allbirds",
"Alleghany",
"Allen & Overy",
"Allergan",
"Alliance Data Systems",
"Allianz Partners",
"Alloy",
"Allstate",
"Ally Financial",
"Almarai - المراعي",
"Alpargatas S.A.",
"Alpha Sense",
"Alshaya Group",
"AltSchool",
"Altice USA",
"Altria Group",
"Always Hired",
"Amaris",
"Amazon",
"Ambev",
"Ambient.ai",
"Amcor",
"Amdocs",
"Amec Foster Wheeler",
"Ameren",
"American Airlines",
"American Axle & Manufacturing",
"American Bar Association",
"American Cancer Society",
"American Electric Power",
"American Express",
"American Family Insurance Group",
"American Financial Group",
"American Heart Association",
"American Marketing Association",
"American Nurses Association",
"American Psychological Association",
"American Red Cross",
"American Society of Civil Engineers",
"American Tower",
"Ameriprise Financial",
"AmerisourceBergen",
"Amgen",
"Amil",
"Amphenol",
"Amplitude Analytics",
"Amway",
"Anadarko Petroleum Corporation",
"Anadarko Petroleum",
"Analog Devices",
"Anaplan",
"Andela",
"Andrade Gutierrez S.A.",
"Angaza",
"AngelList",
"Anglo American",
"AngloGold Ashanti",
"Anheuser-Busch InBev",
"Anheuser-Busch",
"Anixter International",
"Anomali",
"Ansys",
"Anthem",
"Anthropologie",
"Aon",
"Apache Corporation",
"Apache",
"Apex Systems",
"Apollo",
"Apotex Inc.",
"App Academy",
"App Annie",
"AppDirect",
"AppDynamics",
"AppNexus",
"Appen",
"Apple",
"Applied Materials",
"Appodeal",
"Apptimize",
"Apsen Farmacêutica",
"Apteligent",
"Aptiv"
"Apttus",
"Aquent",
"Arab African International Bank",
"Arab Bank",
"ArabJobs.com",
"Arabian Construction Co.",
"Aramark",
"Aramco",
"Aramex",
"Arcadis",
"ArcelorMittal Brasil",
"ArchDaily",
"Archer Daniels Midland",
"Archirodon Group N.V.",
"Arconic",
"Arezzo&Co",
"Aricent",
"Arista Networks",
"Arla Foods",
"Arm",
"Armory",
"Arrow Electronics",
"Art.com",
"Arthur J. Gallagher",
"Artnet",
"Arup",
"Asana",
"Asbury Automotive Group",
"Ascena Retail Group",
"Asda",
"Asian Paints",
"Ask Media Group",
"Aspiring Minds",
"Assaí Atacadista - GPA",
"Assurant",
"Astellas Pharma US",
"Asurion",
"Atento Brasil",
"Atento",
"Atkins",
"Atlas Professionals",
"Atlassian",
"Atos",
"Atrium LTS",
"Aurora",
"Autism Speaks",
"Auto-Owners Insurance",
"AutoNation",
"AutoZone",
"Autodesk",
"Autoliv",
"Automation Anywhere",
"Automattic",
"Automotive News",
"Avanade",
"Avast",
"Avatier",
"Avaya",
"Avenue Code",
"Avery Dennison",
"Avianca Brasil",
"Aviation Recruiting",
"Aviation Week Network",
"Aviationjobs.me",
"Avis Budget Group",
"Avnet",
"Avon",
"Aymoré Financiamentos - Grupo Santander Brasil",
"Azadea Group",
"Azul Linhas Aéreas Brasileiras",
"Banque Saudi Fransi",
"B. Braun Group",
"B/E Aerospace",
"B2W Digital",
"B3",
"BASF",
"BB&T",
"BBC Studios",
"BBDO Worldwide",
"BBVA",
"BCD Travel",
"BD",
"BDF NIVEA BRASIL",
"BESTSELLER",
"BIC",
"BIG - Bjarke Ingels Group",
"BJ's Wholesale Club",
"BM&F BOVESPA",
"BMC Software",
"BMO Financial Group",
"BMW",
"BNP Paribas Asset Management",
"BNSF Railway",
"BNY Mellon",
"BOMBARDIER",
"BRAC",
"BRF",
"BSI",
"BT",
"BTG Pactual",
"BabyCenter",
"Babylist",
"Bacardi",
"Backerkit",
"Bain & Company",
"BairesDev",
"Baker Hughes",
"Baker McKenzie",
"Balfour Beatty US",
"Ball",
"Banana Republic",
"Banco BV",
"Banco Central do Brasil",
"Banco Fibra",
"Banco Inter",
"Banco Itaú",
"Banco Original",
"Banco PAN",
"Banco Santander",
"Banco do Brasil",
"Banglalink",
"Bank of America",
"Bank of New York Mellon",
"Banque Misr",
"Barilla Group",
"Barracuda",
"Barrick Gold Corporation",
"Barron's",
"Bath & Body Works",
"Bausch + Lomb",
"Baxter International",
"Bayer",
"Bayt.com",
"Bdjobs.com",
"Beacon Roofing Supply",
"Beam Suntory",
"BearingPoint",
"Bebo",
"Bechtel Corporation",
"Becker's Healthcare",
"Beckman Coulter Diagnostics",
"Becton Dickinson",
"Bed Bath & Beyond",
"Bedrock Analytics",
"BeeHealthy",
"Beezwax Datatools",
"Beiersdorf",
"Belcorp",
"Bell Flight",
"Benchmark Capital",
"Benefit Cosmetics",
"Benevity",
"Bentley Systems",
"Berkshire Hathaway",
"Berry Global Group",
"Best Buy",
"Bethesda Softworks",
"BetterUp",
"Betterment",
"Betterworks",
"Bexi",
"Beyond Games",
"BigCommerce",
"Bill & Melinda Gates Foundation",
"Bimbo do Brasil",
"Binti",
"Bio-Rad Laboratories",
"BioMérieux",
"Biogen",
"Biolab Sanus Farmacêutica",
"Biosev",
"Birst",
"BitBucket",
"Bitnami",
"Black & Veatch",
"BlackRock",
"Blackhawk Network",
"Blackstone",
"Bleacher Report",
"Blend",
"Blizzard Entertainment",
"Bloc",
"BloomThat",
"Bloomberg",
"Bloomingdale's",
"Blue River Technology",
"BlueCrew",
"BlueJeans",
"BlueVine",
"Blurb",
"Boehringer Ingelheim",
"Boeing",
"Bolloré Logistics",
"Bolt",
"Bons Fluidos",
"Booking Holdings",
"Booz Allen Hamilton",
"BorgWarner",
"Bosch",
"Bose",
"Boston Consulting Group (BCG)",
"Boston Dynamics",
"Boston Scientific",
"Box",
"Boxbot",
"Boyden",
"Bp",
"BrMalls",
"Bradesco Seguros",
"Bradesco",
"Bradfield School of Computer Science",
"Braintree",
"Branch International",
"Branch",
"Brasil Kirin",
"Brasilseg",
"Braskem",
"Brex",
"Bridgestone Americas",
"Bridgewater Associates",
"Brigade",
"BrightBytes",
"BrightTALK",
"Brighthouse Financial",
"Brightidea",
"Brightpearl",
"Brilliant Ads",
"Bristol Myers Squibb",
"British American Tobacco",
"British Council",
"Broadcom",
"Broadly",
"Brookfield Asset Management",
"Brooksource",
"Brown-Forman",
"Bugcrowd",
"Bugsnag",
"BuildZoom",
"Builders FirstSource",
"BuildingConnected",
"Bukwild",
"Bulgari",
"Bunge",
"Bupa",
"Burberry",
"Bureau Veritas Group",
"Burger King",
"Burlington Stores",
"Business Insider",
"Business Insurance",
"Business Partners Consulting",
"BuzzFeed",
"ByteDance",
"C&A Brasil",
"C.H. Robinson",
"C3",
"C6 Bank",
"CA Global Africa Recruitment",
"CA Technologies",
"CACI International Inc",
"CAF - banco de desarrollo de América Latina",
"CAPES - Coordenação de Aperfeiçoamento de Pessoal de Nível Superior",
"CARE",
"CB&I",
"CBRE",
"CBS",
"CCR S.A.",
"CDW",
"CEB, now Gartner",
"CELINE",
"CEVA Logistics",
"CFA Institute",
"CGI",
"CH2M",
"CHANEL",
"CHEP",
"CHS",
"CIB Egypt",
"CIEE - Centro de Integração Empresa-Escola",
"CMS Energy",
"CNBC Make It",
"CNBC",
"CNET",
"CNN",
"COFCO International",
"CPFL Energia",
"CPG - Click Petróleo e Gás",
"CSC",
"CSX",
"CVC CORP",
"CVS Health",
"CWT",
"Cacau Show",
"Cadence Design Systems",
"Cadre Talent",
"Caesars Entertainment",
"Caixa Econômica Federal",
"California Polytechnic State University",
"CallApp",
"CallidusCloud",
"Calpine",
"Calvin Klein",
"Calzedonia Group",
"Camargo Corrêa Infra",
"Cameron, a Schlumberger company",
"Camil Alimentos S/A",
"Campbell Soup",
"Campsyte",
"Canadian Solar Inc.",
"Canon",
"Canvas Medical",
"Capco",
"Capgemini Invent",
"Capgemini",
"Capital One",
"CarMax",
"Carbon Five",
"Carbon",
"Cardinal Health",
"Careem",
"Career Advancers",
"Cargill",
"Carnival Cruise Line",
"Carrefour Brasil",
"Carrier HVAC",
"Carrot Fertility",
"Carta",
"Cartier",
"Casey's General Stores",
"CashBet",
"Castle",
"Catalent Pharma Solutions",
"Caterpillar",
"Catho",
"Catraca Livre",
"Celanese",
"Celgene",
"Cencosud S.A.",
"Centene",
"Center for Creative Leadership",
"CenterPoint Energy",
"Centers for Disease Control and Prevention",
"Centers for Medicare & Medicaid Services",
"CenturyLink",
"Ceres Imaging",
"Cerner Corporation",
"Charles Schwab",
"Charlton Morris",
"Chartboost",
"Charter Communications",
"Chartio",
"Chase",
"Check Point Software Technologies, Ltd.",
"Checkr",
"Cheddar Inc.",
"Chegg",
"Chemours",
"Cheniere Energy",
"Chesapeake Energy",
"Chevron",
"Chewse",
"Chick-fil-A Corporate",
"Chime",
"Chloé",
"Christian Louboutin",
"Christie's",
"Chubb",
"Cia. Hering",
"Cielo",
"Ciena",
"Cigna",
"Cimed Industria De Medicamentos",
"Cinepolis Corporativo",
"Cintas",
"Circle Medical",
"CircleCI",
"Cisco",
"Citi",
"Citigroup",
"Citizens Financial Group",
"Citrix",
"Civil Engineering Discoveries",
"Civil Maps",
"Clara Analytics",
"Clarins",
"Claro Brasil",
"ClassPass",
"ClearBrain",
"ClearMetal",
"Clearbit",
"Cleveland Clinic",
"Clever",
"ClickUp",
"Clifford Chance",
"Climate Corporation",
"Clorox",
"Cloud4Wi",
"CloudFabrix",
"Cloudbees",
"Cloudera",
"Cloudflare",
"Clover Health",
"Club Med",
"CoInspect",
"Coach",
"Coca-Cola",
"Coda",
"Code Nation",
"Codecademy",
"Codexis",
"Coffee Meets Bagel",
"Cognizant Technology Solutions",
"Cognizant",
"Coinbase",
"Coit Group",
"Coldwell Banker",
"Colgate-Palmolive",
"Collabera Inc.",
"Collective Health",
"Colliers International",
"Collins Aerospace",
"Columbia Journalism Review",
"Columbia Sportswear Company",
"Comau",
"Comcast",
"Comfy",
"Community Health Systems",
"CompTIA",
"Companhia Siderúrgica Nacional",
"Compology",
"Computerworld",
"Conagra Brands",
"Concentrix",
"Concremat Engenharia e Tecnologia",
"Conduent",
"Condé Nast",
"Confidential",
"ConocoPhillips",
"Consolidated Contractors International Company",
"Consolidated Edison",
"Constellation Brands",
"Construtora Queiroz Galvão Brasil",
"Construtora Tenda",
"Convergys",
"Converse",
"Copper",
"Core-Mark Holding",
"CoreOS",
"Corning",
"Corteva Agriscience",
"Cosan",
"Costco Wholesale",
"Coty",
"Council on Foreign Relations",
"Coursera",
"Covance",
"Covestro",
"Covidien (Medtronic Minimally Invasive Therapies Group)",
"Cradlepoint",
"Creative Artists Agency",
"Creative Circle",
"Creative Market",
"Credit Karma",
"Credit Suisse",
"Creditas",
"Cricket Health",
"Criteo",
"Crossover for Work",
"Crowdcast",
"Crown Holdings",
"Cruise Automation",
"Crunchbase",
"Crunchyroll",
"Crédit Agricole CIB",
"Culture Amp",
"Cummins Inc.",
"Cummins",
"Curriculum.com.br",
"Cushman & Wakefield",
"Cvent",
"CyberCoders",
"CyberCube",
"Cyient",
"Cypress HCM",
"Cyrela",
"D.R. Horton",
"DCP Midstream",
"DDB",
"DENSO",
"DHL",
"DIRECTV",
"DISH Network",
"DISYS",
"DIY",
"DNAnexus",
"DNEG",
"DNV GL",
"DOHA BANK",
"DOLCE&GABBANA S.r.l",
"DSJ Global",
"DSM",
"DTE Energy",
"DXC Technology",
"DaVita Kidney Care",
"DaVita",
"Dafiti",
"Daily Kos",
"Dana",
"Danaher",
"Danfoss",
"Danish Refugee Council / Dansk Flygtningehjælp",
"Danone",
"Dar",
"Daraz",
"Darden Restaurants",
"Dasa",
"Dassault Systèmes",
"Data Science Central",
"DataCamp",
"DataFox",
"Databricks",
"Datadog",
"Dataminr",
"DeVere Group",
"Dealpath",
"Dean Foods",
"DeepMind",
"Deeplearning.ai",
"Deepnote",
"Deere",
"Defense Intelligence Agency",
"Defense News",
"Delek US Holdings",
"Dell EMC",
"Dell",
"Deloitte",
"Delphi",
"Delta Air Lines",
"Demandbase",
"Dentsu Aegis Network",
"Design Action Collective",
"DesignMap",
"Desigual",
"Deutsche Bank",
"Devon Energy",
"Diageo",
"Dialpad",
"Diamond Offshore",
"Dick's Sporting Goods",
"Diebold Nixdorf",
"Digiday",
"Digitalist Global",
"Digitas North America",
"Dillard's",
"Dimension Data",
"Discord",
"Discover Financial Services",
"Discovery Inc",
"Discovery",
"Disney",
"Disqus",
"Divvy Homes",
"Docker",
"Docker, Inc",
"DocuSign",
"Docusign",
"Dollar General",
"Dollar Tree",
"Dominion Energy",
"Domino's",
"Domo, Inc.",
"Donaldson",
"DoorDash",
"Dover",
"Dow AgroSciences",
"Dow",
"Drake & Scull International PJSC",
"DreamWorks Animation",
"Drogaria São Paulo S.A",
"DroneDeploy",
"Dropbox",
"DuPont de Nemours",
"DuPont",
"Dubai Jobs",
"Duke Energy",
"Duncan Channon",
"Dunnhumby",
"Duolingo",
"Duratex",
"DynCorp International",
"Dyson",
"E*TRADE",
"E3melBusiness",
"EBay",
"EDP",
"EF Education First",
"ELLE Magazine",
"EMCOR Group",
"EMI Music",
"EMS",
"EOG Resources",
"EPAM Systems",
"EQ Recruiting",
"ERE",
"ERecruiter",
"ESPN",
"EVA pharma",
"EXAME",
"EXL",
"EY",
"Earnest",
"EarthStream Global",
"Eastman Chemical",
"EasyPost",
"Eat Club",
"Eataly",
"Eaton",
"Eatsa",
"Eaze",
"Ecolab",
"EdSurge",
"Edelman",
"Edison International",
"Education Week",
"Edward Jones",
"Edwards Lifesciences",
"Eero",
"Ejento",
"Elanco",
"Elastic",
"Elastic.co",
"Electrolux",
"Electronic Arts",
"Elegant Themes",
"Eli Lilly",
"Eliassen Group",
"Elm Company",
"Elsevier",
"Elsewedy Electric",
"Embraer",
"Embratel",
"Emerson",
"Employbl",
"Empregos.com.br",
"EnLink Midstream",
"Endpoint Clinical",
"Energisa",
"Energy Transfer",
"Eneva",
"Engadget",
"Engineering Consultants Group S.A.",
"Entelo",
"Entergy",
"Enterprise Products Partners",
"Enterprise Rent-A-Car",
"Entrepreneur Media",
"Envoy",
"Enwoven",
"Epic Games",
"Epic",
"Epsilon",
"Equinix",
"Equinor",
"Ericsson",
"Erie Insurance Group",
"Eskom Holdings SOC Ltd",
"Esri",
"Essilor Group",
"Essity",
"Estagiários.com",
"Estee Lauder",
"Estágio Online",
"Etisalat Misr",
"Etsy",
"Eurasia Group",
"Eurofarma",
"Euromonitor International",
"Even Construtora",
"Even.com",
"Eventbrite",
"Everis",
"Everlane",
"Evernote",
"Eversource Energy",
"Exelon",
"Expedia Group",
"Expeditors Intl. of Washington",
"Expeditors",
"Expensify",
"Experian",
"Experis",
"Expleo Group",
"Exponential",
"Express Employment Professionals",
"Express Scripts",
"Extole",
"Exxon Mobil",
"F5",
"FAO",
"FCA Fiat Chrysler Automobiles",
"FDA",
"FDM Group",
"FEMA",
"FHI 360",
"FICO",
"FIS",
"FLSmidth",
"FMC Corporation",
"Fabric Genomics",
"Facebook",
"Faire",
"Falconi",
"Fannie Mae",
"Farfetch",
"Farmers Insurance",
"Fast Company",
"FedEx",
"Federal Aviation Administration",
"Federal Bureau of Investigation (FBI)",
"Ferring Pharmaceuticals",
"Fibria",
"Fidelity Investments",
"Fidelity National Financial",
"Fifth Third Bancorp",
"Figure Eight",
"Fin",
"FinancialForce",
"Fingerprint Digital",
"Fini Brasil",
"Fircroft",
"FireEye, Inc.",
"Firjan",
"Firmenich",
"First American Financial",
"First Data Corporation",
"First Data",
"First Point Group",
"First Round Capital",
"First Solar",
"FirstEnergy",
"Fiserv",
"Fisher Investments",
"FitBit",
"Fitbit",
"Five9",
"Fiverr",
"Fivestars",
"Fivetran",
"Flex",
"Flexport",
"Flowserve Corporation",
"Fluor Corporation",
"Fluor",
"Folha de S.Paulo",
"Fond",
"Foot Locker",
"Forbes",
"Ford Motor",
"Forever 21",
"Forkable",
"Formation",
"Forrester",
"Fortinet",
"Fortive",
"Fortune Magazine",
"Forward",
"Fossa",
"Fossil Group, Inc.",
"Foster + Partners",
"Founders Fund",
"Four Seasons Hotels and Resorts",
"Fox",
"Foxconn",
"Fractal",
"Franklin Resources",
"Franklin Templeton",
"Freddie Mac",
"FreeWire Technologies",
"Freelance",
"Freeport-McMoRan",
"Fresenius Medical Care North America",
"Freshworks",
"Frog",
"Front App",
"Frontier Communications",
"Frost & Sullivan",
"Fugro",
"Fundbox",
"FundersClub",
"G4S",
"GE",
"GEODIS",
"GHD",
"GKN Aerospace",
"GLG",
"GM Financial",
"GOL Linhas Aéreas",
"GOLD FIELDS",
"GQR Global Markets",
"GRU Airport - Aeroporto Internacional de São Paulo",
"GRUNDFOS",
"GSK",
"GTBank",
"GUESS?, Inc.",
"Gafisa",
"Gainsight",
"Galderma",
"Gallagher",
"Galvanize",
"GameStop",
"Gameloft",
"Gap",
"Gartner",
"Gemalto (now Thales Digital Identity & Security)",
"GenapSys",
"Genentech",
"General Assembly",
"General Dynamics Information Technology",
"General Dynamics",
"General Electric",
"General Mills",
"General Motors",
"Genesys",
"Genomic Health",
"Genpact",
"Gensler",
"Genuine Parts",
"Genworth Financial",
"Georgia-Pacific LLC",
"Gerdau",
"Getaround",
"Getnet Brasil",
"Getty Images",
"GfK",
"Gigster",
"Gilead Sciences",
"Giorgio Armani",
"GitHub",
"GitLab",
"Givecampus",
"Gladly",
"Glassdoor",
"Glenmark Pharmaceuticals",
"Gliffy",
"Global Empregos Ltda",
"Global Partners",
"GlobalLogic",
"Globant",
"Globo.com",
"Globosat",
"Glu Mobile",
"GoDaddy",
"GoPro",
"Goldcorp",
"Golder",
"Goldman Sachs",
"Gomes da Costa (Calvo Group)",
"Gong.io",
"Good Eggs",
"GoodData",
"Goodby Silverstein & Partners",
"Google",
"Gorgias",
"Grab",
"Grainger",
"Grameenphone Ltd",
"Grammarly",
"Grant Thornton LLP",
"Graphic Packaging Holding",
"Graybar Electric",
"Green Key Resources",
"Greenhouse Software",
"Grendene S/A",
"Grey Group",
"Greystar",
"Grin",
"Groove Labs",
"Group 1 Automotive",
"GroupM",
"Groupe Renault",
"Groupe TF1",
"Groupon",
"Grove Collaborative",
"Grovo",
"GrowthX",
"Grupo Arcor",
"Grupo Boticário",
"Grupo Camargo Corrêa",
"Grupo Cia de Talentos",
"Grupo EcoRodovias",
"Grupo Edson Queiroz",
"Grupo Estado",
"Grupo Fleury",
"Grupo Marista",
"Grupo Netshoes",
"Grupo NotreDame Intermédica",
"Grupo Pao de Acucar",
"Grupo People RH",
"Grupo Petrópolis",
"Grupo RBS",
"Grupo Selpe Recursos Humanos",
"Grupo Tigre",
"Guardian Life Ins. Co. of America",
"Gucci",
"Guerlain",
"Gul Ahmed Textile Mills Limited",
"Gulf Connexions",
"Gulfstream Aerospace",
"Gumroad",
"Gusto",
"Gymboree Group",
"Gympass",
"H&M",
"H&R Block",
"H-E-B",
"HARMAN International",
"HBO",
"HCA Healthcare",
"HCL Technologies",
"HCOR",
"HD Supply Holdings",
"HDI Seguros",
"HDR",
"HELLA",
"HERE Technologies",
"HOK",
"HP",
"HRCI",
"HSBC",
"HUGO BOSS",
"Habitat for Humanity International",
"Hack Reactor",
"HackerEarth",
"HackerOne",
"HackerRank",
"Halliburton",
"Hamad Medical Corporation",
"Hamburg Süd",
"Hammerhead",
"Handy",
"Hanesbrands",
"Hapag-Lloyd AG",
"Harley-Davidson",
"Harnham",
"Harris Corporation",
"Hartford Financial Services",
"Harvard Business Review",
"Hasbro",
"Hassan Allam Holding",
"Havas",
"Haven",
"Hays Executive",
"Hays",
"Headspace",
"Heap",
"HeartFlow",
"Heidrick & Struggles",
"HelloFresh",
"HelloSign",
"Helpshift",
"Henkel",
"Henry Schein",
"Herbalife Nutrition",
"Hermès",
"Hertz",
"Hess",
"Hewlett Packard Enterprise",
"Hill International, Inc.",
"Hill+Knowlton Strategies",
"Hilti Group",
"Hilton",
"Hims",
"HintMD",
"Hire Heroes USA",
"Hire Rightt - Executive Search",
"HireClub",
"HireMilitary",
"Hired",
"Hiretual",
"Hiring Our Heroes",
"Hiring",
"Hitachi Vantara",
"Hitachi",
"Hogan Lovells",
"Holberton School",
"HollyFrontier",
"Homebase",
"Honda",
"Honeybook",
"Honeywell",
"Hoodline",
"Hootsuite",
"Horizons School of Technology",
"Hormel Foods",
"Hornblower Cruises",
"Hospital 9 de Julho",
"Hospital Albert Einstein",
"Hospital Alemão Oswaldo Cruz",
"Hospital São Camilo SP",
"Hospital Sírio-Libanês",
"HotPads",
"HotSchedules",
"Hotel Jobs Worldwide",
"HotelTonight",
"Hotwire",
"Hover",
"Huawei",
"HubSpot",
"Hudson Global",
"Hudson RPO",
"HuffPost",
"Huge",
"Hulu",
"Human Resources Development Fund - HRDF - KSA",
"Human Rights Watch",
"Humana",
"Huntington Ingalls Industries",
"Huntsman",
"Hustle",
"Huxley",
"Hyatt Hotels Corporation",
"Hyatt Regency",
"Hydrogen Group",
"Hypera",
"Hyundai Motor",
"IBM",
"ICON plc",
"IDC",
"IDEMIA",
"IDEO",
"IEEE",
"IFC - International Finance Corporation",
"IFFCO Group",
"IFood",
"IGN Entertainment",
"IHS Markit",
"IHeartMedia",
"IMG",
"IMS Health",
"INTL FCStone",
"IProspect",
"IPsoft",
"IQVIA Holdings",
"IQVIA",
"ITC Hotels",
"Icahn Enterprises",
"Ideo",
"Ifanr",
"Illinois Tool Works",
"Illumina",
"Imgur",
"Imperva",
"In Job",
"InMobi",
"Inbound Logistics",
"Inc. Magazine",
"Indeed",
"Indiegogo",
"Industrial Light & Magic",
"Infineon Technologies",
"InfluxData",
"InfoJobs",
"InfoMoney",
"Infor",
"Informatica",
"Infosys",
"Ingersoll Rand",
"Ingram Micro",
"Ingredion",
"Inman News",
"Inside Higher Ed",
"Insider Inc.",
"Insider",
"Insight",
"Insightly",
"Insikt",
"Instacart",
"Instagram",
"Intel",
"Intelliswift",
"Inter-American Development Bank",
"InterContinental Hotels Group (IHG®)",
"Intercom",
"Intercontinental Exchange",
"Interesting Engineering",
"Interior Design Magazine",
"Internal Revenue Service",
"International Air Transport Association (IATA)",
"International Flavors & Fragrances",
"International Monetary Fund",
"International Paper",
"International Rescue Committee",
"International SOS",
"Interpublic Group",
"Intertek",
"Intuit",
"Investec",
"Invitae",
"Ipiranga",
"Iris Automation",
"Iron Mountain",
"Ironclad",
"Istoe Dinheiro",
"ItaúBBA",
"Iterable",
"J. Walter Thompson Worldwide",
"J.B. Hunt Transport Services",
"J.C. Penney",
"J.Crew",
"J.M. Smucker",
"J.P. Morgan",
"JAC Recruitment Group",
"JACOBS DOUWE EGBERTS",
"JBS",
"JCB",
"JCPenney",
"JLL",
"Chase",
"JSL S.A.",
"Jabil",
"Jacobs Engineering Group",
"Jacobs",
"Jaguar Land Rover",
"Jefferies Financial Group",
"JetBlue Airways",
"JetBrains",
"Jimmy Choo",
"JobJenny.com",
"Jobs For U",
"Jobspring Partners",
"Jobtrack Management Services, Dubai, UAE",
"Jobvite",
"Jobzella",
"John Deere",
"Johnson & Johnson",
"Johnson Controls",
"Joint Commission",
"Jones Financial (Edward Jones)",
"Jones Lang LaSalle",
"Joy",
"Joyent",
"Judge Group",
"Jumpshot",
"June Oven",
"Juniper Networks",
"Juniper Square",
"JustAnswer",
"K2 Partnering Solutions",
"KAUST",
"KBC Staffing",
"KBR, Inc.",
"KEO International Consultants",
"KKR & Co. Inc.",
"KLA",
"KONE",
"KPCB",
"KPMG US",
"KUKA",
"Kaggle",
"Kaiser Permanente",
"Kantar",
"Kapwing",
"Karuna Health",
"Kaspersky",
"Kearney",
"Keller Williams Realty, Inc.",
"Kellogg",
"Kelly",
"Kempinski Hotels",
"Kentik",
"Kering",
"Kerry",
"Keurig Dr Pepper",
"KeyCorp",
"Kforce Inc",
"Khan Academy",
"Khatib & Alami",
"Kiewit",
"Kiip",
"Kimberly-Clark",
"Kinder Morgan",
"King Faisal Specialist Hospital and Research Centre (Gen. Org.)",
"Kissmetrics",
"KittyHawk",
"Kiva",
"Klabin",
"Knotel",
"Kohl's",
"Komatsu Construction",
"Kong",
"Kopenhagen e Chocolates Brasil Cacau (Grupo CRM)",
"Korn Ferry",
"Kotak Mahindra Bank",
"Kraft Heinz",
"Kroger",
"Kroton",
"Kuwait Food Company (Americana)",
"Kyokan",
"L Brands",
"L'Oréal",
"L3 Technologies",
"L3Harris Technologies",
"LANXESS",
"LG Electronics",
"LIBBS FARMACÊUTICA LTDA",
"LKQ",
"LLYC",
"LTI - Larsen & Toubro Infotech",
"LUANDRE CONSULTORIA",
"La Repubblica",
"Laboratory Corp. of America",
"LafargeHolcim",
"Lam Research",
"Lancôme",
"Land O'Lakes",
"Landmark Group",
"Landor",
"Las Vegas Sands",
"Lattice",
"Launch Darkly",
"Launchmaps",
"Layer",
"Lazada",
"Leadspace",
"Leanplum",
"Leap Motion",
"Lear",
"Lee Hecht Harrison",
"Leidos Holdings",
"Leidos",
"LendUp",
"Lending Club",
"LendingHome",
"Lendlease",
"Lennar",
"Lenovo",
"Leo Burnett",
"Leonardo",
"Leroy Merlin",
"Level 3 Communications",
"Lever",
"Levi Strauss & Co.",
"Levi Strauss",
"LexisNexis",
"Leão Alimentos e Bebidas",
"Liberty Media",
"Liberty Mutual Insurance",
"Liebherr Group",
"Life Technologies",
"Liftopia",
"LightStep",
"Lightbend",
"Lincoln National",
"Linde",
"LinkedIn",
"Linqia",
"Linx",
"Lionbridge",
"Lionsgate",
"Liq",
"Literably",
"Lithia Motors",
"Lithium Technologies",
"Live Nation Entertainment",
"LiveRamp",
"Livongo",
"Lob",
"Localiza Hertz",
"Lockheed Martin",
"Loews",
"Logikcull",
"Logitech",
"Lojas Americanas S.A.",
"Lojas Renner S.A.",
"Lojas Riachuelo S/A",
"Lonza",
"Looker",
"Louis Berger",
"Louis Vuitton",
"Lowe's",
"Lucasfilm",
"Luma Health",
"Lupin",
"Luxoft",
"Luxottica",
"Lyft",
"Lynda.com",
"Lyte",
"M&T Bank Corp.",
"M. Dias Branco",
"MAC Cosmetics",
"MAHLE",
"MARISA",
"MGM Resorts International",
"MIT Technology Review",
"MODEC, Inc.",
"MOVER",
"MRS Logística S.A.",
"MRV",
"MSC Cruises",
"MSCI Inc.",
"MSD",
"MSX International",
"MUFG",
"Maaden",
"Machine Zone",
"Macquarie Group",
"Macy's",
"Maersk Oil",
"Magazine Luiza",
"Magellan Health",
"Magna International",
"Mailgun",
"Mainz Brady Group",
"Majid Al Futtaim",
"Major League Baseball",
"Makro Brasil",
"Mammoet",
"Manchester United",
"Manpower",
"ManpowerGroup",
"Mansion Global",
"Mapbox",
"Maptalent",
"Marathon Oil",
"Marc Jacobs",
"Marfrig Global Foods",
"Marilan Alimentos S/A",
"Marine Corps Recruiting",
"Markel",
"MarketWatch",
"Marketo",
"Marketo, an Adobe Company",
"Marqeta",
"Marriott International",
"Mars Wrigley",
"Marsh & McLennan",
"Marsh",
"Marvel Entertainment",
"Marvell Semiconductor",
"Mary Kay Global",
"MasTec",
"Masco",
"Mashable",
"Mashery",
"Massachusetts Mutual Life Insurance",
"Massdrop",
"MasterClass",
"Mastercard",
"MathWorks",
"Mattel, Inc.",
"Matter",
"Mattermark",
"Mattermost",
"Matterport",
"Mayo Clinic",
"Mayvenn",
"McAfee",
"McCain Foods",
"McCann Worldgroup",
"McCormick & Company",
"McDermott International Inc.",
"McDonald's",
"McGraw-Hill",
"McGregor Boyall",
"McKesson",
"McKinsey & Company",
"Mead Johnson Nutrition",
"MediaCom",
"MediaTek",
"Medium",
"Medley Indústria Farmacêutica",
"Medrio",
"Medtronic",
"Meliá Hotels International",
"Meltwater",
"MemSQL",
"Memebox",
"Mende Design",
"Mentor Graphics",
"Mercado Libre",
"Mercado Livre Brasil",
"Mercedes-Benz Maybach Fans",
"Mercedes-Benz USA",
"Mercer",
"Merck",
"Mercuri Urval",
"Mercy Corps",
"Merrill Lynch",
"Mesosphere",
"MessageBird",
"MetLife",
"MetaVision",
"Method",
"Metric Insights",
"Metromile",
"Metso",
"Michael Kors",
"Michael Page",
"Michelin",
"Microchip Technology Inc.",
"Micron Technology",
"Microsoft",
"Millennium Hotels and Resorts",
"MillerCoors",
"Millicom (Tigo)",
"Mindshare",
"Mindsource",
"Mindtree",
"Minerva Foods",
"Ministry of Human Resources and Social Development - KSA",
"Ministério da Saúde",
"Minted",
"Mira",
"MissionU",
"MitchelLake Group",
"Mitchell Martin Inc.",
"Mitsubishi Electric Automation, Inc.",
"MixMax",
"Mixpanel",
"Mobily",
"Mode Analytics",
"Model N",
"Modern Healthcare",
"Modis",
"Mohawk Industries",
"Molina Healthcare",
"Molson Coors Brewing",
"Mondelez International",
"Mondo",
"MongoDB",
"Monsanto Company",
"MonshaatSA",
"Monster",
"MoogSoft",
"Morgan Stanley",
"Morningstar",
"Mosaic",
"Motion Recruitment",
"Motionloft",
"Motorola",
"Mott MacDonald",
"Mountain View Staffing",
"MoveWith",
"Movile",
"Moving Picture Company",
"Mozilla",
"MuleSoft",
"Munich Re (Group)",
"Murphy Oil Corporation",
"Murphy USA",
"Mutual of Omaha Insurance",
"Mux",
"MyFitnessPal",
"Mylan",
"Mynd",
"Médecins Sans Frontières (MSF)",
"NASA",
"NBC News",
"NBCUniversal Media, LLC",
"NCC",
"NCR Corporation",
"NCR",
"NEC Corporation",
"NEOM",
"NGL Energy Partners",
"NHS",
"NICE Ltd",
"NIO",
"NOMAC",
"NPR",
"NRG Energy",
"NTT DATA Services",
"NTT Ltd.",
"NVIDIA",
"NVR",
"NXP Semiconductors",
"NYSE",
"Nalco Water, An Ecolab Company",
"Namely",
"Narvar",
"Nasdaq",
"Nation's Restaurant News",
"National Association of REALTORS®",
"National Bank of Kuwait",
"National Basketball Association (NBA)",
"National Football League (NFL)",
"National Geographic",
"National Grid",
"National Instruments",
"National Oilwell Varco",
"National Science Foundation (NSF)",
"National Security Agency",
"Nationwide",
"Natura",
"Nature is Amazing",
"Naughty Dog",
"Navient",
"Navistar International",
"Naytev",
"Neiman Marcus Group",
"Nelson Staffing",
"Neoenergia",
"NepFin",
"Nerd Wallet",
"Nestle",
"NetApp",
"NetSuite",
"Netflix",
"Netlify",
"New Balance",
"New Relic",
"New York Life Insurance",
"New York Post",
"NewCo",
"NewYork-Presbyterian Hospital",
"Newcrest Mining",
"Newell Brands",
"Newfront Insurance",
"Newmont Corporation",
"News Corp.",
"NexTravel",
"Nexa Resources",
"NextEra Energy",
"Nextdoor",
"Nextel Brasil",
"Neyborly",
"Nielsen",
"Nieman Journalism Lab",
"Nike",
"NinjaRMM",
"Nintendo",
"Nissan Motor Corporation",
"No Means No Worldwide",
"NoRedInk",
"Noble Drilling",
"Noble Energy",
"Node.js Foundation",
"Nokia",
"Nomura",
"Noon",
"Nordea",
"Nordstrom",
"Norfolk Southern",
"Northern Trust Corporation",
"Northern Trust",
"Northrop Grumman",
"Northwestern Mutual",
"Norwegian Cruise Line Holdings Ltd.",
"Notable Labs",
"Notion",
"Nova Credit",
"Novartis Institutes for BioMedical Research (NIBR)",
"Novartis Oncology",
"Novartis",
"Novo Nordisk",
"Novo Tempo Consultoria e Recursos Humanos Ltda",
"Novozymes",
"Nubank",
"Nucor",
"Nuna",
"Nuro",
"Nutanix",
"Nvidia",
"Nylas",
"O Boticário",
"O Segredo",
"O'Reilly Automotive",
"OAS S.A.",
"OECD - OCDE",
"OMA",
"ON Semiconductor",
"OYO",
"Oakley",
"Oath",
"Occidental Petroleum",
"Oceaneering",
"Odebrecht",
"Odfjell Drilling",
"Odopod",
"Offensive Security",
"Office Depot",
"Ogilvy",
"Oi",
"Oil And Gas Career",
"Oil and Gas Jobs",
"Okta",
"Olam",
"Old Navy",
"Old Republic International",
"Olin",
"Oliver Wyman",
"Oman Air",
"Oman LNG L.L.C.",
"Omnicom Group",
"Omnicom Media Group",
"One Acre Fund",
"OneLogin",
"Oneok",
"OpenAI",
"OpenDNS",
"OpenText",
"Opendoor",
"Opentable",
"Optimizely",
"Optimus Search",
"Optum",
"Opus Recruitment Solutions",
"Oracle",
"Orange Business Services",
"Orange Egypt",
"Orascom Construction Ltd",
"Orascom Development Egypt",
"Orpic",
"Oscar Health",
"Oshkosh",
"Otis Elevator Co.",
"Ouro Verde",
"Ouster",
"Outreach",
"Owens & Minor",
"Owens Corning",
"Owens-Illinois",
"Oxford University Press",
"Oxiteno",
"Oxy",
"PA Consulting",
"PBF Energy",
"PCL Construction",
"PENTOZ",
"PG&E",
"PIMCO",
"PNC Financial Services",
"PNC",
"PPD",
"PPG Industries",
"PPL",
"PRA Health Sciences",
"PTC",
"PUMA",
"PVH Corp.",
"PVH",
"Paccar",
"Pacific Gas and Electric Company",
"Pacific Life",
"Packaging Corp. of America",
"PagSeguro PagBank",
"Page Personnel",
"PagerDuty",
"Pakistan Placement",
"Paladin",
"Palo Alto Networks",
"Palo Alto Staffing",
"Panalpina",
"Panasonic North America",
"Pandora",
"Panoply",
"Pantheon",
"Pantone",
"Paramount Pictures",
"Parexel",
"Parker Hannifin",
"Parker and Lynch",
"Parsable",
"Parsons Corporation",
"Patagonia",
"PayPal",
"Paycom",
"Peabody Energy",
"Pearson",
"Pegasystems",
"Penguin Random House",
"Penske Automotive Group",
"Pentagram",
"Pentair",
"PeopleConnect Staffing",
"PeopleGrove",
"PepsiCo",
"Pequenas Empresas & Grandes Negócios",
"Percolate",
"Perfetti Van Melle",
"Performance Food Group",
"Performance Horizon",
"Periscope",
"Perkins and Will",
"Pernambucanas",
"Pernod Ricard",
"Persistent Systems",
"Peter Kiewit Sons'",
"Petrobras",
"Petroleum Development Oman",
"Petroplan",
"Petz - O seu Pet Center de Estimação",
"Pfizer",
"Philip Morris International",
"Philips",
"Phillips 66",
"Philo",
"Pierre Fabre Group",
"Pif Paf Alimentos",
"PingWest",
"Pinterest",
"Pioneer Natural Resources",
"Pique Tea",
"Piracanjuba",
"Pirelli",
"Pivotal",
"Pixar Animation Studios",
"Pixlee",
"Pizza Hut",
"Plaid",
"Plains GP Holdings",
"PlanGrid",
"Planet Pharma",
"Planet",
"Planetizen",
"PlayStation",
"Polaris Industries",
"Poly",
"Porsche Cars North America",
"Porto Seguro",
"Portrait Displays",
"Poshmark",
"Post Holdings",
"Postman",
"Postmates",
"Practice Fusion",
"Pramp",
"Pratt & Whitney",
"Premier Talent Partners",
"Prezi",
"Principal Financial",
"Privalia",
"Procter & Gamble",
"Product School",
"Progressive Recruitment",
"Progressive",
"Project Management Institute",
"Projeto Draft",
"Pronaca",
"Proteus Digital Health",
"Protiviti",
"Proto.io",
"Prudential Financial",
"Prysmian Group",
"Psychology Today",
"Public Health England",
"Public Investment Fund (PIF)",
"Public Relations Society of America (PRSA)",
"Public Service Enterprise Group",
"Publicis Media",
"Publicis",
"Publix Super Markets",
"PulteGroup",
"Puratos",
"Pure Storage",
"Pusher",
"PwC Brasil",
"PwC",
"QNB Group",
"Qadium",
"Qatar Airways",
"Qatar Foundation",
"Qatar Petroleum",
"Qatargas",
"Qiddiya Investment Company | شركة القدية للاستثمار",
"Qlik",
"Qualcomm",
"Qualia",
"Qualtrics",
"Qualys",
"Quanta Services",
"Quantcast",
"Quartz",
"Quest Diagnostics",
"Quid",
"QuintoAndar",
"Quip",
"Quora",
"Qurate Retail",
"Qwilt",
"R.R. Donnelley & Sons",
"R/GA",
"RANDON S.A.",
"RB",
"RBC Capital Markets",
"RBC",
"RE/MAX",
"REED",
"REI",
"RGA Associates",
"RGP",
"RH que Inspira",
"RICS",
"RISMedia",
"RR Donnelley",
"RSA Security",
"Rackspace",
"Radical Designs",
"Radisson Hotel Group",
"Radius",
"RainForest QA",
"Rainmakers",
"RaiseMe",
"Rally Health",
"Ralph Lauren",
"Ramsey Solutions",
"Randstad USA",
"Randstad",
"Rappi",
"Raymond James Financial",
"Raytheon",
"RazorFrog",
"Raízen",
"ReKrute.com | Premier sur l'emploi",
"ReadMe",
"Real Estate Updates",
"RealPage, Inc.",
"Realogy Holdings",
"Realtor.com",
"Receita Federal",
"Recode",
"RecruitingBlogs.com",
"Recurly",
"Red Bridge Internet",
"Red Bull",
"Red Hat",
"Red Oak Technologies",
"Redbubble",
"Reddit",
"Rede D'Or São Luiz",
"Rede Globo",
"Redfin",
"Redpoint Ventures",
"Reebok",
"ReferralExchange",
"Refinery29, Inc.",
"Reflektive",
"Reforge",
"Regeneron Pharmaceuticals",
"Regions Financial",
"Regus",
"Reinsurance Group of America",
"Reliance Steel & Aluminum",
"Remind",
"Remix",
"Repsol",
"Republic Services",
"Rescale",
"Reserva",
"Resilio",
"Restless Bandit",
"Resultados Digitais",
"Returnly",
"Revista Manutenção",
"Revlon Inc.",
"Richemont",
"Ridecell",
"Rigetti Computing",
"Rigzone",
"RingCentral",
"Rio Tinto",
"Riot Games",
"Rite Aid",
"Rithm School",
"Riviera Partners",
"Riyad Bank",
"Roadshow",
"Robert Half International",
"Robert Half",
"Robert Walters",
"Robi Axiata Limited",
"Roche",
"Rocket Lawyer",
"RocketSpace",
"Rockstar Games",
"Rockwell Automation",
"Rockwell Collins",
"Rollbar",
"Rolls-Royce",
"Roofstock",
"Rosewood Hotels & Resorts",
"Ross Stores",
"Ross Stores, Inc.",
"Rotary International",
"Rothschild & Co",
"Royal Caribbean Cruises Ltd.",
"Runway Incubator",
"Russell Reynolds Associates",
"Russell Tobin",
"Rx Technology",
"Ryder System",
"Rylo",
"S&P Global Market Intelligence",
"S&P Global",
"SABB",
"SABIC",
"SAIC",
"SANS Institute",
"SAP SuccessFactors",
"SAP",
"SAS",
"SAUDI AIRLINES",
"SBM Offshore",
"SBT",
"SC Johnson",
"SDL plc",
"SEBRAE",
"SEPHORA",
"SHRM",
"SIAC Construction",
"SITA",
"SKY Brasil",
"SOLIDWORKS",
"SONDA",
"SQM",
"SUEZ - Water Technologies & Solutions",
"SV Angel",
"SWAROVSKI",
"Saatchi & Saatchi",
"Saba Software",
"Sabre Corporation",
"Sadara Chemical Company",
"Safeway",
"Safra",
"Safran – Aircraft Interiors",
"Sage",
"Saint Laurent",
"Saks Fifth Avenue",
"Sales Humor",
"Salesforce",
"Salon Media Group",
"Salt",
"Sam's Club",
"Samsara",
"Sandoz",
"Sandvik",
"Sanmina",
"Sano",
"Sanofi Genzyme",
"Sanofi",
"Santander Bank, N.A.",
"Santander Universidades - Brasil",
"Sapient",
"SapientRazorfish",
"Saraiva",
"Sasol",
"Sauce Labs",
"Saudi Aramco Total Refining and Petrochemical Company (SATORP)",
"Saudi Authority for Industrial Cities and Technology Zones",
"Saudi Credit Bureau - SIMAH",
"Saudi Electricity Company",
"Saudi Stock Exchange (TADAWUL)",
"Savola Group",
"SavvyMoney",
"Say Media",
"Scal.io",
"Scalable Press",
"Scality",
"Schaeffler",
"Schindler Group",
"Schlumberger",
"Schneider Electric",
"ScienceDaily",
"Scion Staffing",
"Scottish Development International",
"Scripted",
"Scrum Alliance",
"Scrum.org",
"Seaboard",
"Seadrill",
"Seagate Technology",
"Seara Alimentos LTDA",
"Sears",
"Securitas Security Services USA, Inc.",
"Securly",
"Segment",
"Selby Jennings",
"Sempra Energy",
"Senac",
"Sendwithus",
"Sentry",
"Sepam",
"Sephora",
"Sequoia Capital",
"Serasa Experian",
"Serco",
"ServiceNow",
"Shangri-La Group",
"Shell",
"Sheraton Hotels & Resorts",
"Sherwin-Williams",
"Shift.org",
"Shipt",
"Shiseido",
"ShopPad",
"Shopify",
"Shoulder",
"Shutterfly",
"Sicoob",
"Sicredi",
"Siemens",
"Sift Science",
"Sight Machine",
"Simon Property Group",
"Simon Sinek Inc.",
"Simplilearn",
"Sindeo",
"Sitel",
"Sizmek",
"Skanska",
"Skedulo",
"Skidmore, Owings & Merrill (SOM)",
"Skift",
"Skillz",
"Slack",
"Slalom Consulting",
"SlashNext",
"Slashdot Media",
"Slow Ventures",
"Smarking",
"SmartBiz Loans",
"Smiles",
"Smith & Nephew",
"SmugMug",
"Smurfit Kappa",
"Snapchat",
"SnapLogic",
"Snapdocs",
"Snappr",
"Snowflake",
"SoFi",
"Societe Generale Corporate and Investment Banking - SGCIB",
"Society of Petroleum Engineers International",
"Sodexo",
"Softtek",
"Sogeti",
"Solar Turbines",
"SolarCity",
"Solenis",
"SoloLearn",
"Solomon Page",
"Solvay",
"Sonatrach",
"Sonder",
"Sonic Automotive",
"Sony",
"Sophos",
"Sotheby's",
"Sotreq S/A",
"Sourceress",
"Southern",
"Southwest Airlines",
"SpaceX",
"Spark Program",
"Sparkart",
"Sparkcentral",
"SpartanNash",
"Spectrum",
"Spencer Ogden",
"Spencer Stuart",
"Spirit AeroSystems Holdings",
"Splunk",
"SpotX",
"Spotify",
"Spotinst",
"SpringML",
"Springboard",
"Sprinklr",
"Sprint",
"Square",
"St. Jude Medical",
"Stack Overflow",
"Stackshare",
"Stamen Design",
"Stanley Black & Decker",
"Staples",
"Starbucks",
"Starcity",
"Starcom",
"Starwood Hotels & Resorts Worldwide, Inc.",
"Stash Invest",
"State Farm",
"State Street Corp.",
"State Street",
"Statoil",
"Stc",
"Steel Dynamics",
"Steelcase",
"Stefanini Brasil",
"Stella McCartney",
"Stitch Fix",
"Stitch Labs",
"Stitcher",
"Stone",
"Storenvy",
"Strategy&",
"Stratim",
"Strava",
"Streak CRM",
"Stripe",
"Strive Talent",
"Stryker",
"StubHub",
"StumbleUpon",
"Subsea 7",
"Subway",
"SulAmérica Seguros Saúde",
"Sumo Logic",
"Sun Life",
"Sun Microsystems",
"SunTrust Banks",
"Supervalu",
"Sura",
"Sutherland",
"Suzano",
"Swatch Group",
"Sweco",
"Swift Navigation",
"SwiftStack",
"Swiftly",
"Swiss Re",
"Swissport",
"Swrve",
"Syapse",
"Syllable.ai",
"Symantec",
"SyncFab",
"Synchrony",
"Synechron",
"Syneos Health Clinical Solutions",
"Syneos Health",
"Syngenta",
"Synnex",
"Synopsys Inc",
"Syntel",
"Sysco",
"T-Mobile",
"T-Systems International GmbH",
"TAM",
"TASC Outsourcing",
"TBWA Worldwide",
"TD",
"TE Connectivity",
"TED Conferences",
"TED Talks",
"TEKsystems",
"TIAA",
"TIBCO",
"TIM Brasil",
"TIME",
"TIVIT",
"TJX",
"TOTVS",
"TRS Staffing Solutions",
"TSMC",
"TTEC",
"Tableau Software",
"Takeda",
"Talabat",
"Talener",
"Talent",
"Talentburst",
"Talkable",
"Talkdesk",
"Tangent International",
"Taos",
"Tapestry",
"Targa Resources",
"Target",
"Tarte Cosmetics",
"TaskRabbit",
"Tata Group",
"Teach For America",
"Teachers Pay Teachers",
"Teamable",
"Tech Data",
"Tech Liminal",
"Tech Mahindra",
"TechConnexion",
"TechCrunch",
"TechSoup",
"Techees Recruiting",
"Techint Engineering & Construction",
"Technicolor",
"TechnipFMC",
"Tecoloco.com",
"Teekay",
"Teespring",
"Tegra Incorporadora",
"Tekfen Construction",
"Telecom Egypt",
"Telia",
"Temenos",
"Tenable",
"Tenaris",
"Tencent",
"Tenet Healthcare",
"Tenneco",
"Teradata",
"Terminus Software",
"Ternium",
"Tesla",
"Tetra Pak",
"Tetra Tech",
"Tetra",
"Teva Pharmaceuticals",
"Texas Instruments",
"Textron",
"Thalmic Labs",
"The American Institute of Architects (AIA)",
"The Associated Press",
"The Athletic",
"The Atlantic",
"The Body Shop",
"The Brutal Truth about Sales & Selling PodCast - on all your favorite PodCast Players",
"The Business of Fashion",
"The Carlyle Group",
"The Chronicle of Higher Education",
"The Church of Jesus Christ of Latter-day Saints",
"The Clorox Company",
"The Economist",
"The Estée Lauder Companies Inc.",
"The Goodyear Tire & Rubber Company",
"The Green Recruitment Company",
"The Heineken Company",
"The Hacker News",
"The Hershey Company",
"The Hive",
"The Home Depot",
"The International Civil Aviation Organization",
"The Janssen Pharmaceutical Companies of Johnson & Johnson",
"The Judge Group",
"The Kraft Heinz Company",
"The LEGO Group",
"The League",
"The Metropolitan Museum of Art",
"The Motley Fool",
"The Museum of Modern Art",
"The National Institutes of Health",
"The Nature Conservancy",
"The New York Times",
"The New Yorker",
"The North Face, a VF Company",
"The RealReal",
"The Red Sea Development Company",
"The Ritz-Carlton Hotel Company, L.L.C.",
"The Sourcery",
"The TOEFL test",
"The Trade Desk",
"The Verge",
"The Wall Street Journal",
"The Washington Post",
"The We Company",
"The World Bank",
"TheWrap",
"Thermo Fisher Scientific",
"Thirdlove",
"Thomson Reuters",
"Thor Industries",
"ThoughtWorks",
"ThousandEyes",
"Thrive Global",
"Thrivent Financial for Lutherans",
"Thumbtack",
"Thunder",
"Thyssenkrupp",
"Ticket",
"TietoEVRY",
"Tiffany & Co.",
"Tiger Brands",
"TikTok",
"Tirolez",
"Toastmasters International",
"Tok&Stok",
"Tokio Marine Seguradora",
"Toll Brothers",
"Tommy Hilfiger",
"Too Faced Cosmetics",
"Tophatter",
"Tory Burch",
"Townsquared",
"Toyota",
"Traction",
"Tractor Supply",
"Tradecraft",
"Tradeshift",
"Trafigura",
"Trane",
"TransPerfect",
"TransUnion",
"TravelCenters of America",
"Travelers",
"Traveloka",
"Travelport",
"Tray.io",
"TreeHouse Foods",
"Trend Micro",
"Trifacata",
"Trina Solar",
"Tripadvisor",
"Triplebyte",
"Trulia",
"Truly",
"TrustArc",
"Turner & Townsend",
"Turner (Turner Broadcasting System, Inc)",
"Turner Construction Company",
"Turo",
"TwentyThree",
"Twilio",
"Twitch",
"Twitter",
"Tyson Foods",
"U.N.A.M. facultad de ingenieria",
"U.S. Bancorp",
"U.S. Bank",
"U.S. Department of Health and Human Services (HHS)",
"U.S. Department of Homeland Security",
"U.S. Department of State",
"U.S. Department of Veterans Affairs",
"U.S. Secret Service",
"UBS Investment Bank",
"UCB",
"UGI",
"UL",
"UN Women",
"UNDP",
"UNICEF",
"UNIQLO",
"UNOPS",
"UNRWA",
"UOL",
"UPS Supply Chain Solutions",
"UPS",
"URS Corporation, An AECOM Company",
"US Army Corps of Engineers",
"US Army",
"US Environmental Protection Agency (EPA)",
"US Foods Holding",
"US Foods",
"US Navy",
"US Tech Solutions",
"USA TODAY",
"USAA",
"USAID",
"USAJOBS",
"USIMINAS",
"UST Global",
"UTC Aerospace Systems",
"Uber",
"Ubisoft",
"Udacity",
"Udemy",
"UiPath",
"Ulta Beauty",
"Ultracargo",
"Under Armour",
"Unilever",
"Unimed do Brasil",
"Unimed",
"Union Pacific",
"Unisys",
"United Airlines",
"United Continental Holdings",
"United Nations OCHA",
"United Nations Population Fund (UNFPA)",
"United Nations Volunteers",
"United Nations",
"United Natural Foods",
"United Parcel Service",
"United Rentals",
"United States Air Force",
"United States Department of Defense",
"United States Postal Service",
"United States Steel",
"United Technologies",
"UnitedHealth Group",
"Unity Technologies",
"Univar Solutions",
"Univar",
"Universal Health Services",
"Universal Pictures",
"University of Utah - Employment",
"Univision Communications Inc.",
"União Química Farmacêutica Nacional",
"Unum Group",
"Upgrade",
"Upsight",
"Upwork",
"Urban Airship",
"Urban Decay Cosmetics",
"Urban Outfitters",
"UrbanSitter",
"User Testing Inc.",
"VAGAS.com",
"VF Corporation",
"VF",
"VICE Media",
"VLI Logística",
"VMWare",
"VMware",
"VON DER HEIDE",
"VSCO",
"Vaco",
"VagasEmbarcado.com",
"Vale",
"Valeo",
"Valero Energy",
"ValiMail",
"Valor Econômico S/A",
"Valve corporation",
"Van Cleef & Arpels",
"Vanguard",
"Vans, a VF Company",
"Varian Medical Systems",
"Variety",
"Veeam Software",
"VentureBeat",
"Verbal + Visual",
"Veritiv",
"Verizon",
"Verkada",
"Vero",
"Versace",
"Vertex Pharmaceuticals",
"Vestas",
"Veterans Employment",
"Vevo",
"Via Transportation",
"Via Varejo SA",
"Viacom",
"Victoria's Secret",
"Vidado",
"VigLink",
"Vigor Alimentos",
"Vineti",
"Virtusa",
"Visa",
"Visby",
"Vistra Energy",
"Vitagene",
"Vitra",
"Vivara",
"Vivo (Telefônica Brasil)",
"Vodafone",
"Vogue",
"Voiceops",
"Volkswagen",
"Volt - International",
"Volt Workforce Solutions",
"Volvo",
"Vonnda",
"Votorantim Cimentos",
"Votorantim",
"Voxbone",
"Voya Financial",
"Vungle",
"W Hotels",
"W.R. Berkley",
"W.W. Grainger",
"WEC Energy Group",
"WEG",
"WESCO International",
"WGSN",
"WIRED",
"WRS - Worldwide Recruitment Solutions",
"WTS Energy",
"WUZZUF",
"WWD",
"WWF",
"Wake",
"Walgreens Boots Alliance",
"Walgreens",
"Wall Chase",
"Wallstreetcn.com",
"Walmart",
"Wanelo",
"Warner Bros. Entertainment",
"Waste Management",
"Watsi",
"WayUp",
"Wayfair",
"WazaefAlyoum.com - وظائف اليوم",
"We Are Social",
"WePay",
"WeWork",
"Wealthfront",
"Weatherford",
"Weber Shandwick",
"Webflow",
"Weebly",
"WellCare Health Plans",
"WellnessFX",
"Wells Fargo",
"WestRock",
"Western & Southern Financial Group",
"Western Digital",
"Western Union",
"Westin Hotels & Resorts",
"Westlake Chemical",
"Weyerhaeuser",
"Wheelwell",
"Whirlpool Corporation",
"Whirlpool",
"White Martins",
"Whole Foods Market",
"Wieden + Kennedy",
"Wikia",
"Williams",
"Williams-Sonoma",
"Willis Towers Watson",
"Windstream Holdings",
"Wipro Limited",
"Wipro Ltd. - India",
"Wish",
"Wizeline",
"Woebot Labs",
"Wollborg Michelson Recruiting",
"Wolters Kluwer",
"Womply",
"Wonderschool",
"Wonderware",
"Woopra",
"Workbridge Associates",
"Workday",
"World Bank Group",
"World Economic Forum",
"World Fuel Services",
"World Health Organization",
"World Vision",
"World Wide Technology",
"World Wildlife Fund",
"Worldpay",
"Wounded Warrior Project",
"Wunderman",
"Wyndham Destinations",
"Wynn Resorts",
"Wyser",
"Wärtsilä",
"XP Investimentos",
"XPO Logistics",
"XPO Logistics, Inc.",
"XTO Energy",
"Xcel Energy",
"Xero",
"Xerox",
"Xilinx",
"Xoriant",
"Y Combinator SF",
"Yahoo",
"Yale University Careers",
"Yammer",
"Yanbal",
"Yara International",
"Yelp",
"Yext",
"Yodlee",
"Yoh, A Day & Zimmermann Company",
"Yokogawa",
"YouGov",
"YouTube",
"Young & Rubicam",
"Ypê",
"Yum Brands",
"Yum China Holdings",
"Yum! Brands",
"ZALORA Group",
"ZDNet",
"ZF Group",
"ZS",
"Zain KSA",
"Zain",
"Zalando SE",
"Zapier",
"Zazzle",
"Zebra Technologies",
"Zedo",
"Zendesk",
"Zendrive",
"Zenefits",
"Zenput",
"Zenreach",
"Zensar Technologies",
"Zenysis",
"ZeroCater",
"Zignal Labs",
"Zimmer Biomet",
"Zinc",
"Zodiac Aerospace",
"Zoetis",
"Zoho Corporation",
"Zoosk",
"Zume Pizza",
"Zumper",
"Zuora",
"Zurich Insurance Company Ltd",
"Zycus",
"Zynga",
"comma.ai",
"eBay",
"enSilo",
"iCrossing",
"iHear Medical",
"iHeartMedia",
"inDinero",
"interviewing.io",
"npm Inc",
"salesforce.com",
"trendmedia",
"uBiome"]
companies_set = set()

for company in companies:
    companies_set.add(company)

result = '['

for company in companies_set:
    result += "\"" + company + "\"," + '\n'

result += ']'

print(result)

pyperclip.copy(result)